

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto1.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Proyecto1Entities : DbContext
{
    public Proyecto1Entities()
        : base("name=Proyecto1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ContactUs> ContactUs { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<ListaVenta> ListaVenta { get; set; }

    public virtual DbSet<Venta> Venta { get; set; }

}

}

